### ISSUE TITLE
Liquid error: comparison of String with 'number'

### ISSUE THREAD

**Issue by dobseh** [Shopify/liquid#1061]
This is an issue generated within a Huginn Agent, but as it seems to be a problem with Liquid rather than Huginn I'm hoping someone here can help.

I'm using the Huginn Message Formatting agent to create the body of an email with data obtained from the Dark Sky weather API. The API outputs the wind direction in degrees (0 being north) which I am trying to convert into text using the following

```
{% if avewind.degrees >= 316 OR avewind.degrees <= 45 %}north{% endif %}
{% if avewind.degrees >= 46 and avewind.degrees <= 125 %}east{% endif %}
{% if avewind.degrees >= 126 and avewind.degrees <= 230 %}south{% endif %}
{% if avewind.degrees >= 231 and avewind.degrees <= 315 %}west{% endif %}
```

However this produces the following error

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Dry Run failed
[00:00:00] ERROR -- : Exception during dry-run. Liquid error: comparison of String with 360 failed: /app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:117:in `rescue in interpret_condition'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:114:in `interpret_condition'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:44:in `evaluate'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:43:in `block (2 levels) in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:41:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
/app/app/concerns/liquid_interpolatable.rb:106:in `block (2 levels) in interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:105:in `catch'
/app/app/concerns/liquid_interpolatable.rb:105:in `block in interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:104:in `interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:83:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:86:in `block (2 levels) in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:85:in `each'
/app/app/concerns/liquid_interpolatable.rb:85:in `each_with_object'
/app/app/concerns/liquid_interpolatable.rb:85:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:86:in `block (2 levels) in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:85:in `each'
/app/app/concerns/liquid_interpolatable.rb:85:in `each_with_object'
/app/app/concerns/liquid_interpolatable.rb:85:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:99:in `block in interpolated'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:97:in `interpolated'
/app/app/models/agents/event_formatting_agent.rb:130:in `block (3 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/event_formatting_agent.rb:212:in `apply_compiled_matchers'
/app/app/models/agents/event_formatting_agent.rb:129:in `block (2 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/event_formatting_agent.rb:128:in `block in receive'
/app/app/models/agents/event_formatting_agent.rb:127:in `each'
/app/app/models/agents/event_formatting_agent.rb:127:in `receive'
/app/app/concerns/dry_runnable.rb:29:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/base.rb:194:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications.rb:168:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications.rb:168:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/base.rb:134:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1.1/lib/action_view/rendering.rb:32:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal.rb:191:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal.rb:252:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:35:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:38:in `call_app'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:26:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/static.rb:127:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/engine.rb:524:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

```

I've tried adding `{% assign avewind.degrees = avewind.degrees | plus: 0 %}` prior to the comparison, but this still returns the same error.

The input JSON from the API looks like:

```
{
  "date": {
    "epoch": "1549065600",
    "pretty": "12:00 AM GMT on February 02, 2019",
    "day": 2,
    "month": 2,
    "year": 2019,
    "yday": 33,
    "hour": 0,
    "min": "00",
    "sec": 0,
    "isdst": 0,
    "monthname": "February",
    "monthname_short": "Feb",
    "weekday_short": "Sat",
    "weekday": "Saturday",
    "ampm": "AM",
    "tz_short": "GMT"
  },
  "period": 0,
  "high": {
    "fahrenheit": "38",
    "epoch": "1549116000",
    "fahrenheit_apparent": "29",
    "epoch_apparent": "1549076400",
    "celsius": "3"
  },
  "low": {
    "fahrenheit": "32",
    "epoch": "1549148400",
    "fahrenheit_apparent": "21",
    "epoch_apparent": "1549148400",
    "celsius": "0"
  },
  "conditions": "Mostly cloudy until afternoon.",
  "icon": "partly-cloudy-day",
  "avehumidity": 87,
  "sunriseTime": "1549093064",
  "sunsetTime": "1549126474",
  "moonPhase": "0.93",
  "precip": {
    "intensity": "0.0021",
    "intensity_max": "0.0212",
    "intensity_max_epoch": "1549065600",
    "probability": "0.67",
    "type": "snow"
  },
  "dewPoint": "31.62",
  "avewind": {
    "mph": "14",
    "kph": "23",
    "degrees": "316"
  },
  "visibility": "10",
  "cloudCover": "0.36",
  "pressure": "1006.11",
  "ozone": "409.32",
  "location": "00.959339,-00.308"
}
```
Enclosing the values to be tested against in single quotes like

```
{% if avewind.degrees >= '316' OR avewind.degrees <= '45' %}north{% endif %}
{% if avewind.degrees >= '46' and avewind.degrees <= '125' %}east{% endif %}
{% if avewind.degrees >= '126' and avewind.degrees <= '230' %}south{% endif %}
{% if avewind.degrees >= '231' and avewind.degrees <= '315' %}west{% endif %}
```

But this produces some really odd results, such as a a value of 0 to 99 returning "north", anything between 100 to 125 returning nothing at all.  Values after 126 return results in the correct output however.

Any help gratefully received!

**Comment by dobseh** [comment]
The dev over on the Huginn github worked this out, so for anyone else who happens to come across this, the answer is that you can't do the comparison against a sub variable. So when you convert the String to a Number you have to also change the variable to be a "top level" one.

So in my case doing 

```
{% assign degrees = avewind.degrees | plus: 0 %}
```

and then removing the single quotes around the values to be compared like

```
{% if degrees <= 360 and degrees >= 316 %}north{% endif %}
{% if degrees <= 45 and degrees >= 0 %}north{% endif %}
{% if degrees <= 99 and degrees >= 46 %}east{% endif %}
{% if degrees <= 125 and degrees >= 100 %}east{% endif %}
{% if degrees <= 230 and degrees >= 126 %}south{% endif %}
{% if degrees <= 315 and degrees >= 231 %}west{% endif %}
```
Makes the comparision work correctly. Will close this issue, but think the wiki could use something to indicate that variables have to be re-assigned when doing comparision.
