### ISSUE TITLE
Error mode setting does not apply

### ISSUE THREAD

**Issue by greenfork** [Shopify/liquid#1389]
Setting error mode doesn't seem to affect anything for version 5.0
```ruby
require 'liquid'

Liquid::Template.parse('{{a}', :error_mode => :warn)  # raises
Liquid::Template.parse('{{a}')  # raises
```
```
Traceback (most recent call last):
	9: from /tmp/t1.rb:4:in `<main>'
	8: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/template.rb:97:in `parse'
	7: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/template.rb:110:in`parse'
	6: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/document.rb:7:in `parse'
	5: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/document.rb:23:in `parse'
	4: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/document.rb:55:in `parse_body'
	3: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:29:in `parse'
	2: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:143:in `parse_for_document'
	1: from /home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:236:in `create_variable'
/home/grfork/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:75:in `raise_missing_variable_terminator': Liquid syntax error: Variable '{{a}' was not properly terminated with regexp: /\\}\\}/ (Liquid::SyntaxError)
```

**Comment by bobbytables** [comment]
+1 - Also experiencing this

**Comment by greenfork** [comment]
Still relevant for 5.1

**Comment by dylanahsmith** [comment]
Are you saying that this only warned before version 5.0?  Since I think it has behaved like this since the first liquid commit and isn't related to the strict error mode.

When https://github.com/shopify/liquid#error-modes says

> Normally the parser is very lax and will accept almost anything without error.

this is one of those few exceptions.

I'll try to clarify the documentation a bit for this case.
