### ISSUE TITLE
unable to load code in irb, cannot load such file -- liquid/resource_limits [trivial]

### ISSUE THREAD

**Issue by siscia** [Shopify/liquid#509]
Hi everybody,

sorry for bothering you with this trivial issues.

Most likely the problem is me don't know ruby enough, however is a couple of days that I try to figure this issues out.

I want to explore the codebase more deeply, so I got the code from here and I was hoping to run it in the irb, however I keep get an exception:

``` bash
simo@simo:~$ cd liquid/
simo@simo:~/liquid$ ls
CONTRIBUTING.md  Gemfile     lib             MIT-LICENSE  Rakefile   test
example          History.md  liquid.gemspec  performance  README.md
simo@simo:~/liquid$ cat lib/liquid/version.rb 
# encoding: utf-8
module Liquid
  VERSION = "3.0.0"
end
simo@simo:~/liquid$ irb -I . -rubygems
irb(main):003:0> require 'lib/liquid.rb'
LoadError: cannot load such file -- liquid/resource_limits
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /home/simo/liquid/lib/liquid.rb:66:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from (irb):3
	from /usr/bin/irb:12:in `<main>'
```

What I am doing wrong ?

Cheers

Simone

**Comment by fw42** [comment]
Try "irb -I lib" and then just "require liquid"

**Comment by siscia** [comment]
Thank you :)

Really sorry about that...
