### ISSUE TITLE
closed tag is reported as never closed

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#656]
Running into a very strange bug indeed on `master`:

``` text
Liquid Exception: Liquid syntax error: 'highlight' tag was never closed in /Users/parker/code/benbalter.github.com/_posts/2015-09-10-blog-style-tests.md
/usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block.rb:56:in `block in parse_body': Liquid syntax error: 'highlight' tag was never closed (Liquid::SyntaxError)
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block_body.rb:48:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block.rb:51:in `parse_body'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block.rb:10:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/tag.rb:10:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block_body.rb:26:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block.rb:51:in `parse_body'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block.rb:10:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/tag.rb:10:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/block_body.rb:26:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/document.rb:10:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/document.rb:5:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/template.rb:120:in `parse'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/bundler/gems/liquid-89ccdabe9a3f/lib/liquid/template.rb:105:in `parse'
    from /Users/parker/jekyll/jekyll/lib/jekyll/liquid_renderer/file.rb:11:in `block in parse'
    from /Users/parker/jekyll/jekyll/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
    from /Users/parker/jekyll/jekyll/lib/jekyll/liquid_renderer/file.rb:10:in `parse'
    from /Users/parker/jekyll/jekyll/lib/jekyll/renderer.rb:97:in `render_liquid'
    from /Users/parker/jekyll/jekyll/lib/jekyll/renderer.rb:54:in `run'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:171:in `block (2 levels) in render'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:169:in `each'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:169:in `block in render'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:168:in `each'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:168:in `render'
    from /Users/parker/jekyll/jekyll/lib/jekyll/site.rb:59:in `process'
    from /Users/parker/jekyll/jekyll/lib/jekyll/command.rb:28:in `process_site'
    from /Users/parker/jekyll/jekyll/lib/jekyll/commands/build.rb:60:in `build'
    from /Users/parker/jekyll/jekyll/lib/jekyll/commands/build.rb:35:in `process'
    from /Users/parker/jekyll/jekyll/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /usr/local/var/rbenv/versions/2.1.6-github1/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/parker/jekyll/jekyll/bin/jekyll:17:in `<main>'
```

but at the same time

``` text
~/code/benbalter.github.com#master$ ag highlight _posts/2015-09-10-blog-style-tests.md
22:{% highlight ruby %}
31:{% endhighlight %}
43:{% highlight ruby %}
58:{% endhighlight %}
68:{% highlight ruby %}
80:{% endhighlight %}
92:{% highlight ruby %}
96:{% endhighlight %}
```

Looks perfectly legit.

**Comment by fw42** [comment]
Is this this file https://github.com/benbalter/benbalter.github.com/blob/master/_posts/2015-09-10-blog-style-tests.md?

**Comment by parkr** [comment]
Yes!
