### ISSUE TITLE
UndefinedDropMethod missing `line_number`

### ISSUE THREAD

**Issue by leoc** [Shopify/liquid#819]
I am using Liquid 4.0.0.rc3 from master. When a template is having runtime errors I am missing the `line_number` information from the error object.

```ruby
str = 'Test Template: {{ object.resource.typ }}'
liquid = Liquid::Template.parse(str, error_mode: :strict)
# object is an ActiveRecord model finding the `belongs_to` resource
puts liquid.render({ 'object' => object }, { strict_variables: true }) 
liquid.errors.first
# => #<Liquid::UndefinedDropMethod: Liquid error: undefined method typ>
```

The backtrace:

```
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/drop.rb:29:in `liquid_method_missing'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/drop.rb:37:in `invoke_drop'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/context.rb:215:in `lookup_and_evaluate'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/variable_lookup.rb:48:in `block in evaluate'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/variable_lookup.rb:38:in `each_index'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/variable_lookup.rb:38:in `evaluate'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/context.rb:179:in `evaluate'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/variable.rb:76:in `render'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/block_body.rb:109:in `render_node'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/block_body.rb:88:in `block in render'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/block_body.rb:75:in `each'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/block_body.rb:75:in `render'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/template.rb:203:in `block in render'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/template.rb:237:in `with_profiling'
/usr/local/bundle/bundler/gems/liquid-86944fe7b777/lib/liquid/template.rb:202:in `render'
```

**Comment by dylanahsmith** [comment]
You need to pass the option `line_numbers: true` to Liquid::Template.parse, e.g. `Liquid::Template.parse(source, line_numbers: true)`
